name: Deploy ExpressJS App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Setup the SSH key
      - name: Setup SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem  # Write the SSH key to a file
          chmod 600 private_key.pem  # Secure the private key file

      # Step 3: Copy files to EC2 instance
      - name: Copy files to EC2
        run: |
          rsync -avz -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/Kurunegala-Cabs-Back-End
          # This syncs your local repo files to the EC2 instance's Kurunegala-Cabs-Back-End directory.

      # Step 4: Install dependencies and restart the app using PM2
      - name: Install dependencies and restart app
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/Kurunegala-Cabs-Back-End  # Navigate to your app directory
            npm install  # Install any new dependencies
            pm2 stop Kurunegala-Cabs-App || true  # Stop the app if it's running (ignore error if not running)
            pm2 start server.js --name Kurunegala-Cabs-App --watch  # Start/restart the app and enable file watching
            pm2 save  # Save the PM2 process list so it persists on reboot
          EOF
